services:
  db:
    image: mysql:8
    container_name: mysql-local
    restart: unless-stopped  # 시스템 재시작 후 자동 부팅
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-local
    hostname: rabbit-host
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: test
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management UI
    networks:
      - backend

networks:
  backend:
    driver: bridge
